sudo: required
language: go
go:
- '1.13'
script:
- make
- npm install -g snyk
- make snyk
services:
- docker
before_deploy:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- pip install --user awscli==1.16.242
deploy:
- provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
    # Snyk token
    - secure: "H0gUcu2QSs9woFV+0xz9D2AkdEIONGeqRZ+Kts07PTYNS9SKvap48nSFaBygvU5Q2NW+9+yEtZoh4t+DN3KtnC4mEkTQZ63oDeqpafBOAyk41GQIZP8pNU3W3S++cAMRcy31k8OxAWxlHSJSwvROyjbN2lxC/r0EKMwGzkyWQQcJT446NNJ4Vpj+NS10C8iHCOGmXVQXaig+V9Crq6PC1xAV0Pfcm3cb08VMqdI3Qm9annzLklaWMIVPvvyaNoGb7WKd4croXBnOn6uvK5497Oypeer63dVaBxKVhkeaKF9KviF+5fKrC+9q+qXSMcjvHgE2tSosHKE/3F7sGhbQDqbsRYtWxyeseqlJ/H5DPJdD4csTPVJlOHuC1z0CxLFMRMzT0k22cgVzii6o2wKbS98tpXk1muNdaPtZvaHynT64VmmO5htrAHGUcHjMlRdidtnRNABhp18D4A1UsASPG+zV7KGmSNWExgTLQttseNSOyvxZ9jUAv6ys2r/9puHJbC/m/rdTjwwbx8hI1govq0WG5GwNXMyNBgiZv2GSHoK56BvXDOWDL3MyrwuiC7FIk/1jY0rhYwtGTLxeExYIdtkxpnvWn3m9QhHt3RzV1e09Hwwi1SuU3oV+/DhvsdCMcvNj6a+AyAYbujKkV/EkQz/VgSv9X+NIrzRxvsLG0eE="
