FROM alpine:3.9

RUN apk add --no-cache --upgrade \
        ca-certificates \
        musl=1.1.20-r4

USER nobody
COPY nri-discovery-kubernetes /bin/nri-discovery-kubernetes

ENTRYPOINT ["/bin/nri-discovery-kubernetes"]